export const stations = [
  { id: 1, stationName: "Gombak", line: "KJL" },
  { id: 2, stationName: "Taman Melati", line: "KJL" },
  { id: 3, stationName: "Wangsa Maju", line: "KJL" },
  { id: 4, stationName: "Sri Rampai", line: "KJL" },
  { id: 5, stationName: "Setiawangsa", line: "KJL" },
  { id: 6, stationName: "Jelatek", line: "KJL" },
  { id: 7, stationName: "Datuk Keramat", line: "KJL" },
  { id: 8, stationName: "Damai", line: "KJL" },
  { id: 9, stationName: "Kampung Baru", line: "KJL" },
  { id: 10, stationName: "KLCC", line: "KJL" },
  { id: 11, stationName: "Kampung Baru North", line: "KJL" },
  { id: 12, stationName: "Dang Wangi", line: "KJL" },
  { id: 13, stationName: "Masjid Jamek", line: "KJL" },
  { id: 14, stationName: "Pasar Seni", line: "KJL" },
  { id: 15, stationName: "Merdeka", line: "KJL" },
  { id: 16, stationName: "Pasar Seni South", line: "KJL" },
  { id: 17, stationName: "Bukit Nanas", line: "KJL" },
  { id: 18, stationName: "Dang Wangi South", line: "KJL" },
  { id: 19, stationName: "Kampung Baru South", line: "KJL" },
  { id: 20, stationName: "KLCC East", line: "KJL" },
  { id: 21, stationName: "KLCC North", line: "KJL" },
  { id: 22, stationName: "KL Sentral", line: "KJL" },
  { id: 23, stationName: "KL Sentral North", line: "KJL" },
  { id: 24, stationName: "Bangsar South", line: "KJL" },
  { id: 25, stationName: "Angkasapuri", line: "KJL" },
  { id: 26, stationName: "University", line: "KJL" },
  { id: 27, stationName: "Taman Jaya", line: "KJL" },
  { id: 28, stationName: "Asia Jaya", line: "KJL" },
  { id: 29, stationName: "Taman Paramount", line: "KJL" },
  { id: 30, stationName: "Kelana Jaya", line: "KJL" },
  { id: 31, stationName: "Lembah Subang", line: "KJL" },
  { id: 32, stationName: "Ara Damansara", line: "KJL" },
  { id: 33, stationName: "Glenmarie", line: "KJL" },
  { id: 34, stationName: "Subang Jaya", line: "KJL" },
  { id: 35, stationName: "SS15", line: "KJL" },
  { id: 36, stationName: "SS18", line: "KJL" },
  { id: 37, stationName: "USJ 7", line: "KJL" },
  { id: 38, stationName: "Taipan", line: "KJL" },
  { id: 39, stationName: "Wawasan", line: "KJL" },
  { id: 40, stationName: "USJ 21", line: "KJL" },
  { id: 41, stationName: "Alam Megah", line: "KJL" },
  { id: 42, stationName: "Subang Alam", line: "KJL" },
  { id: 43, stationName: "Putra Heights", line: "KJL" },
  { id: 44, stationName: "Ampang", line: "AGL" },
  { id: 45, stationName: "Cahaya", line: "AGL" },
  { id: 46, stationName: "Cempaka", line: "AGL" },
  { id: 47, stationName: "Pandan Indah", line: "AGL" },
  { id: 48, stationName: "Pandan Jaya", line: "AGL" },
  { id: 49, stationName: "Maluri", line: "AGL" },
  { id: 50, stationName: "Miharja", line: "AGL" },
  { id: 51, stationName: "Pudu", line: "AGL" },
  { id: 52, stationName: "Hang Tuah", line: "AGL" },
  { id: 53, stationName: "Plaza Rakyat", line: "AGL" },
  { id: 54, stationName: "Masjid Jamek", line: "AGL" },
  { id: 55, stationName: "Dang Wangi", line: "AGL" },
  { id: 56, stationName: "Kampung Baru", line: "AGL" },
  { id: 57, stationName: "Jelatek", line: "AGL" },
  { id: 58, stationName: "Dato Keramat", line: "AGL" },
  { id: 59, stationName: "Setiawangsa", line: "AGL" },
  { id: 60, stationName: "Wangsa Maju", line: "AGL" },
  { id: 61, stationName: "Sri Rampai", line: "AGL" },
  { id: 62, stationName: "Taman Melati", line: "AGL" },
  { id: 63, stationName: "Sentul Timur", line: "SP" },
  { id: 64, stationName: "Sentul", line: "SP" },
  { id: 65, stationName: "Titiwangsa", line: "SP" },
  { id: 66, stationName: "PWTC", line: "SP" },
  { id: 67, stationName: "Sultan Ismail", line: "SP" },
  { id: 68, stationName: "Bandaraya", line: "SP" },
  { id: 69, stationName: "Masjid Jamek", line: "SP" },
  { id: 70, stationName: "Plaza Rakyat", line: "SP" },
  { id: 71, stationName: "Pudu", line: "SP" },
  { id: 72, stationName: "Hang Tuah", line: "SP" },
  { id: 73, stationName: "Chan Sow Lin", line: "SP" },
  { id: 74, stationName: "Cheras", line: "SP" },
  { id: 75, stationName: "Salak Selatan", line: "SP" },
  { id: 76, stationName: "Bandar Tun Razak", line: "SP" },
  { id: 77, stationName: "Bandar Tasik Selatan", line: "SP" },
  { id: 78, stationName: "Sungai Besi", line: "SP" },
  { id: 79, stationName: "Bukit Jalil", line: "SP" },
  { id: 80, stationName: "Sri Petaling", line: "SP" },
  { id: 81, stationName: "Awan Besar", line: "SP" },
  { id: 82, stationName: "Muhibbah", line: "SP" },
  { id: 83, stationName: "Alam Sutera", line: "SP" },
  { id: 84, stationName: "Kinrara BK5", line: "SP" },
  { id: 85, stationName: "IOI Puchong Jaya", line: "SP" },
  { id: 86, stationName: "Pusat Bandar Puchong", line: "SP" },
  { id: 87, stationName: "Taman Perindustrian Puchong", line: "SP" },
  { id: 88, stationName: "Bandar Puteri", line: "SP" },
  { id: 89, stationName: "Puchong Perdana", line: "SP" },
  { id: 90, stationName: "Puchong Prima", line: "SP" },
  { id: 91, stationName: "Putra Heights", line: "SP" },
  { id: 92, stationName: "Kwasa Damansara", line: "KGL" },
  { id: 93, stationName: "Kwasa Sentral", line: "KGL" },
  { id: 94, stationName: "Kota Damansara", line: "KGL" },
  { id: 95, stationName: "Surian", line: "KGL" },
  { id: 96, stationName: "Mutiara Damansara", line: "KGL" },
  { id: 97, stationName: "Bandar Utama", line: "KGL" },
  { id: 98, stationName: "Taman Tun Dr Ismail", line: "KGL" },
  { id: 99, stationName: "Phileo Damansara", line: "KGL" },
  { id: 100, stationName: "Pusat Bandar Damansara", line: "KGL" },
  { id: 101, stationName: "Semantan", line: "KGL" },
  { id: 102, stationName: "Muzium Negara", line: "KGL" },
  { id: 103, stationName: "Pasar Seni", line: "KGL" },
  { id: 104, stationName: "Merdeka", line: "KGL" },
  { id: 105, stationName: "Bukit Bintang", line: "KGL" },
  { id: 106, stationName: "Tun Razak Exchange", line: "KGL" },
  { id: 107, stationName: "Cochrane", line: "KGL" },
  { id: 108, stationName: "Maluri", line: "KGL" },
  { id: 109, stationName: "Taman Pertama", line: "KGL" },
  { id: 110, stationName: "Taman Midah", line: "KGL" },
  { id: 111, stationName: "Taman Mutiara", line: "KGL" },
  { id: 112, stationName: "Taman Connaught", line: "KGL" },
  { id: 113, stationName: "Taman Suntex", line: "KGL" },
  { id: 114, stationName: "Sri Raya", line: "KGL" },
  { id: 115, stationName: "Bandar Tun Hussein Onn", line: "KGL" },
  { id: 116, stationName: "Batu 11 Cheras", line: "KGL" },
  { id: 117, stationName: "Bukit Dukung", line: "KGL" },
  { id: 118, stationName: "Sungai Jernih", line: "KGL" },
  { id: 119, stationName: "Stadium Kajang", line: "KGL" },
  { id: 120, stationName: "Kajang", line: "KGL" },
  { id: 121, stationName: "Kwasa Damansara", line: "PYL" },
  { id: 122, stationName: "Kampung Selamat", line: "PYL" },
  { id: 123, stationName: "Sungai Buloh", line: "PYL" },
  { id: 124, stationName: "Damansara Damai", line: "PYL" },
  { id: 125, stationName: "Sri Damansara Barat", line: "PYL" },
  { id: 126, stationName: "Sri Damansara Sentral", line: "PYL" },
  { id: 127, stationName: "Sri Damansara Timur", line: "PYL" },
  { id: 128, stationName: "Metro Prima", line: "PYL" },
  { id: 129, stationName: "Kepong Baru", line: "PYL" },
  { id: 130, stationName: "Jinjang", line: "PYL" },
  { id: 131, stationName: "Sri Delima", line: "PYL" },
  { id: 132, stationName: "Kampung Batu", line: "PYL" },
  { id: 133, stationName: "Kentonmen", line: "PYL" },
  { id: 134, stationName: "Jalan Ipoh", line: "PYL" },
  { id: 135, stationName: "Sentul Barat", line: "PYL" },
  { id: 136, stationName: "Titiwangsa", line: "PYL" },
  { id: 137, stationName: "Hospital Kuala Lumpur", line: "PYL" },
  { id: 138, stationName: "Raja Uda", line: "PYL" },
  { id: 139, stationName: "Ampang Park", line: "PYL" },
  { id: 140, stationName: "Persiaran KLCC", line: "PYL" },
  { id: 141, stationName: "Conlay", line: "PYL" },
  { id: 142, stationName: "Tun Razak Exchange (TRX)", line: "PYL" },
  { id: 143, stationName: "Chan Sow Lin", line: "PYL" },
  { id: 144, stationName: "Bandar Malaysia Utara", line: "PYL" },
  { id: 145, stationName: "Bandar Malaysia Selatan", line: "PYL" },
  { id: 146, stationName: "Kuchai", line: "PYL" },
  { id: 147, stationName: "Taman Naga Emas", line: "PYL" },
  { id: 148, stationName: "Sungai Besi", line: "PYL" },
  { id: 149, stationName: "Serdang Raya Utara", line: "PYL" },
  { id: 150, stationName: "Serdang Raya Selatan", line: "PYL" },
  { id: 151, stationName: "Serdang Jaya", line: "PYL" },
  { id: 152, stationName: "UPM", line: "PYL" },
  { id: 153, stationName: "Taman Equine", line: "PYL" },
  { id: 154, stationName: "Putra Permai", line: "PYL" },
  { id: 155, stationName: "16 Sierra", line: "PYL" },
  { id: 156, stationName: "Cyberjaya Utara", line: "PYL" },
  { id: 157, stationName: "Cyberjaya City Centre", line: "PYL" },
  { id: 158, stationName: "Putrajaya Sentral", line: "PYL" },
];
